' /* Copyright Yahoo, Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms. */

@startwbs RiskRemediation
!theme plain

<style>
wbsDiagram {
  .riskremediation {
      BackgroundColor lightblue
  }
  .risk {
      BackgroundColor pink
  }
  .asset {
      BackgroundColor orange
  }
  .remediation {
      BackgroundColor lightgreen
  }
}

</style>

Title Risk Remediation Taxonomy for CVEs/vulnerabilities

* **Risk Remediation** <<riskremediation>>

**[#pink]:==Per Vulnerability 
----
----
----;


***[#pink] **Threat**




****_ **Likelihood of Exploitation** How likely is it to be exploited? 
*****_ **Known Evidence or Activity**
******_ **Known Actively Exploited in your Organization**
*******_ <:closed_book:> **Bug Bounty** has the CVE been exploited?
*******_ <:closed_book:> **Incident Response** has the CVE been exploited? 
******_ **Known Actively Exploited in the Wild**
*******_ <:green_book:> **CISA KEV** Known Exploited Vulnerabilities
*******_ <:green_book:> <:dollar:> **Cyber Threat Intelligence (CTI)** e.g. social media, vendors
******_ **Weaponized Exploit** ready to run in a tool or script
*******_ <:green_book:>** MetaSploit** 
*******_ <:green_book:>** Nuclei** 
*******_ <:dollar:>** Vendor DBs** which may include other sources
******_ **Proof Of Concept Exploit** proof-of-concept exploit code exists
*******_ <:green_book:>** ExploitDB** 
*******_ <:green_book:>** GitHub** 
*******_ <:dollar:>** Vendor DBs** which may include other sources


*****_  <:green_book:> **Probability of Exploitation Activity in the next 30 days % **(EPSS Exploit Prediction Scoring System v3) which covers the range of proability from 0 to 1.

****_ **Exploitability Metrics ** How easy is it to exploit? e.g. is it easily automated. [CVSS Base Metric - Exploitability Metrics]
*****_ <:green_book:> **Attack Vector** 
*****_ <:green_book:> **Attack Complexity** 
*****_ <:green_book:> **Attack Requirements** [CVSS Base Metric v4]
*****_ <:green_book:> **Privileges Required** 
*****_ <:green_book:> **User Interaction** 

****_ <:green_book:> <:dollar:> **Report Confidence**
***** Not Defined, Unknown, Confirmed, Reasonable [CVSS Temporal]




***[#pink] **Technical Impact**
****_ **System Impact Metrics** 
*****_ <:green_book:> **Vulnerable System Impact Metrics** [CVSS Base Metric]
******_ <:green_book:> **Confidentiality**  
******_ <:green_book:> **Integrity**
******_ <:green_book:> **Availability** 
******_ <:green_book:> --Scope-- [replaced with Subsequent System Impact Metrics in CVSS v4
*****_ <:green_book:> **Subsequent System Impact Metrics** [CVSS Base Metric v4]
******_ <:green_book:> **Confidentiality** 
******_ <:green_book:> **Integrity** 
******_ <:green_book:> **Availability** 



**** **<:green_book:> MITRE CAPEC Technical Impact**
*****_ **Logical Impact Methods**

******_ **Execution (Integrity)  <&play-circle*3>**
*******_ Unauthorized Code or Commands
*******_ Alter Execution Logic
*******_ Unexpected State
******_ **Access (Access Control) <&account-login*3>**
*******_ Gain privileges / assume identity (Access Control)
*******_ Bypass protection mechanism
******_ **Hide activities (Non Repudiation)  <&question-mark*3>**

*****_ **Logical Impact**
******_ **Read (Confidentiality) <&data-transfer-download*3>**
*******_ Read Application Data
*******_ Read Files or Directories
*******_ Read Memory
******_ **Modify (Integrity) <&data-transfer-upload*3>**
*******_ Modify Application Data
*******_ Modify Files or Directories
*******_ Modify Memory
******_ **Denial Of Service (Availability) <&ban*3>**
*******_ Unreliable Execution
********_ Crash, Exit, or Restart
********_ Instability
********_ Amplification
*******_ Resource Consumption 
********_ CPU
********_ Memory
********_ Other

****_ <:green_book:> **Microsoft Exploitability Index** [Microsoft Products]
*****_ Elevation of Privilege
*****_ Remote Code Execution
*****_ Denial of Service
*****_ Information Disclosure
*****_ Security Feature Bypass
*****_ Spoofing
*****_ Tampering



**[#orange]:==Per Asset 
----
----
----;


*** **Threat** <<asset>>
****_ **Likelihood** 
*****_ <:closed_book:> **Incident Response** has the Asset been attacked?
*****_ <:closed_book:> **Number of assets with that CVE (SBOMs)**
*****_ <:closed_book:> **Number of instances of that CVE (SBOMs)**
*****_ **Vulnerability Chaining**
*****_ <:dollar:> **Average Time to Exploit Product (VendorDB)**
*****_ <:dollar:> **Frequency of Exploit for the Product (VendorDB)**

****_ **Exploitable**
*****_ <:closed_book:> **Affected stack component versions in place** e.g. SpringShell Spring Framework exploitability depended on certain JDK versions
*****_ <:closed_book:> **Reachable** e.g. vulnerable function called by Application or callable (Tool e.g. SCA Reachability Analysis)
*****_ <:closed_book:> <:writing_hand:> **Compensating controls in place** e.g. WAF, SW configuration

****_ **System Exposure** 
*****_ <:closed_book:> <:writing_hand:> **Asset Inventory**
***** Small, Controlled, Open [CMU SEI SSVC] 


*** **Technical Impact** <<asset>>

**** **Vulnerability Impact Scoring System (VISS)** the impact on the Confidentiality / Integrity / Availability of the platform/tenants/data involved by the successful exploitation of the security vulnerability found 

****_ <:closed_book:> <:writing_hand:> **Asset Value <Asset Inventory>**
*****_ **Value of the data it processes/serves**
*****_ **Geo location (Regulatory)**
*****_ **Performing Critical function aka Critical Product or Crown Jewel**

*****_ **Requirements for Confidentiality, Integrity, Availability (CIA)**
****** None, Low, Medium, High [CVSS Environmental]


*****_ **Loss** 
****** **Factor Analysis of Information Risk (FAIR)** Productivity, Response, Replacement, Reputation, Competitive advantage, Judgments and fines





** **Remediation** <<remediation>> 
***_ **Remediation Level: patch available?**
****_ <:green_book:> <:dollar:> **Tool e.g. SCA**
****_ <:green_book:> <:dollar:> **Vendor DBs** 

**** Not Defined, Official Fix, Temporary Fix, Workaround, Unavailable [CVSS Temporal]
**** Available, Unavailable [CISA SSVC]
**** Fix, Workaround [CISA SSVC]
***_ <:closed_book:> **System Change difficulty: quick fix or major refactor?**
****_ <:busts_in_silhouette:> **Developers**
**** Low, High [CISA SSVC]
***_ <:closed_book:> **Fix/Merge Confidence** Can we apply the fix? Will the fix break something?
****_ <:green_book:> <:dollar:> **% (Tool e.g. SCA)**
****_ <:busts_in_silhouette:> **Developers**
***_ <:closed_book:> **Package upgrade value**
****_ how many risky CVEs are fixed by updating a package of any version to latest/target version? (SBOMs)
***_ <:closed_book:> **Effort**
****_ <:busts_in_silhouette:> **Developers**
**** CMU SEI discusses “unit of work” for Remediation activitities



legend
    |= Icon |= Description |
    |  <:closed_book:>  | Internal |
    |  <:green_book:>   | Open and available to anyone |
    |  <:dollar:>       | Paid product  |
    |  <:writing_hand:> | Manual |
    |  <:black_square_button:> | Relevant values defined in a standard |
endlegend

center footer <:triangular_flag_on_post:> The data sources for Threat and Vulnerability give information for individual vulnerabilities. For an asset, we're concerned about all the vulnerabilities and threats - including if these are chainable \n <:triangular_flag_on_post:> "vulnerabilities with published exploit code are as much as 7 times as likely to be exploited in the wild" "If it’s ‘weaponized’ (think metasploit), the odds of a vulnerability being exploited in the wild really balloon from about 3.7% to 37.1%." https://www.cyentia.com/github-a-source-for-exploits/ \n <:triangular_flag_on_post:> GitHub Advisory DB, VendorDBs, Tool-providers provide additional vulnerability information that may not have an associated CVE - or may have data that differs from the NVD CVE data. \n <:triangular_flag_on_post:>Asset (~Product) contains Package that contains CVE

@endwbs

Themes
-------
This gives the best clarity
!theme plain 

Other themes considered:
!theme metal
!theme materia
!theme cerulean
!theme hacker

icons
------
https://plantuml.com/creole
https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhDpS_AL31qC-5oICrB0Oe00000

preprocessor
------------
Consider using plantuml pre-processor in future to maintain definitions in one place/file. 
define: !$cisa_kev = "<:green_book:> **CISA Known Exploited Vulnerabilities (CISA KEV)**"
use: $cisa_kev 
