' /* Copyright Yahoo, Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms. */

@startwbs RiskRemediation_top
!theme plain

<style>
wbsDiagram {
  .riskremediation {
      BackgroundColor lightblue
  }
  .risk {
      BackgroundColor pink
  }
  .asset {
      BackgroundColor orange
  }
  .remediation {
      BackgroundColor lightgreen
  }
}

</style>

Title Risk Remediation Taxonomy for CVEs/vulnerabilities

* **Risk Remediation** <<riskremediation>>

**[#pink]:==Per Vulnerability 
----
----
----;


***[#pink] **Threat**
****_ **Evidence or Probability of Exploit Activity** How likely is it to be exploited? e.g. based on known or predicted exploitation activity.
****_ **Exploitability Metrics** How easy is it to exploit? e.g. is it easily automated.

***[#pink] **Impact** 
****_ **Impact** What's the impact of exploitation? e.g. Denial of Service, Files can be read or written.



**[#orange]:==Per Asset 
----
----
----;

*** **Impact** <<asset>> 
****_ **What's the impact on the Asset?** e.g. none due to compensating controls, service disruption,...

*** **Likelihood** <<asset>>
****_ **What's the Likelihood that the Asset will be exploited?** given all the vulnerabilities, compensating controls, runtime context,....



** **Remediation** <<remediation>> 
***_ **How easy is it to fix the vulnerabilities?**


@endwbs

Themes
-------
This gives the best clarity
!theme plain 

Other themes considered:
!theme metal
!theme materia
!theme cerulean
!theme hacker

icons
------
https://plantuml.com/creole
https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhDpS_AL31qC-5oICrB0Oe00000

preprocessor
------------
Consider using plantuml pre-processor in future to maintain definitions in one place/file. 
define: !$cisa_kev = "<:green_book:> **CISA Known Exploited Vulnerabilities (CISA KEV)**"
use: $cisa_kev 
