' /* Copyright Yahoo, Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms. */

@startwbs RiskRemediation
!theme plain

<style>
wbsDiagram {
  .riskremediation {
      BackgroundColor lightblue
  }
  .risk {
      BackgroundColor pink
  }
  .asset {
      BackgroundColor orange
  }
  .remediation {
      BackgroundColor lightgreen
  }
}

</style>

Title Risk Remediation Taxonomy for CVEs

* **Risk Remediation** <<riskremediation>>

**[#pink]:==Per Vulnerability 
----
----
----;


***[#pink] **Threat**

****_ **Likelihood of Exploit**
*****_ **Known Actively Exploited in your Organization**
******_ <:closed_book:> **Bug Bounty** has the CVE been exploited?
******_ <:closed_book:> **Incident Response** has the CVE been exploited? 
*****_ **Known Actively Exploited in the Wild**
******_ <:green_book:> **CISA Known Exploited Vulnerabilities (CISA KEV)**
******_ <:dollar:> **Vendor DBs** (typicaly include CISA KEV data)
******_ <:green_book:> <:dollar:> **Cyber Threat Intelligence (CTI)** e.g. social media
*****_  <:green_book:> **Probability of Exploitation Activity in the next 30 days % **(EPSS Exploit Prediction Scoring System v3)
******_ **Exploitation activity in the wild (ground truth)** Fortinet, AlienVault, ShadowServer, GreyNoise
******_ **Publicly available exploit code** ExploitDB, GitHub, MetaSploit
******_ CVE listed on CISA KEV, Google Project Zero, Trend Micro's Zero Day Initiative
******_ **Social Media** Mentions/discussion on Twitter
******_ **Offensive security tools and scanners** Intrigue, sn1per, jaeles, nuclei
******_ **References with labels** MITRE CVE List, NVD
******_ **Keyword description of the vulnerability** Text description in MITRE CVE List
******_ **CVSS metrics** National Vulnerability Database (NVD)
******_ **CWE** National Vulnerability Database (NVD)
******_ **Vendor labels** National Vulnerability Database (NVD)
******_ **Age of the vulnerability** Days since CVE published in MITRE CVE list
*****_ **Known Exploit Available**
******_ **Weaponized Exploit**
*******_ <:green_book:>** MetaSploit** 
*******_ <:green_book:>** Nuclei** 
*******_ <:dollar:>** Vendor DBs** which may include other sources
******_ **Proof Of Concept Exploit**
*******_ <:green_book:>** ExploitDB** 
*******_ <:green_book:>** GitHub** 
*******_ <:dollar:>** Vendor DBs** which may include other sources
******_ <:green_book:> <:dollar:>  **Cyber Threat Intelligence (CTI)** e.g. social media
******_ <:green_book:> <:dollar:> **Exploit Code Maturity **
*******_ <:dollar:> **Vendor DBs** 
******* Exploit Code Maturity: Not Defined, Unproven, Proof-Of-Concept, Functional, High [CVSS V3 Temporal Metrics]
******* Exploit Maturity: Not Defined, Attacked, Proof-Of-Concept, Unreported   [CVSS V4 Threat Metrics]
******* e.g. public, poc_public, virus_malware, wormified, private, commercial, exploit_unknown, unknown


****_ <:green_book:> <:dollar:> **Report Confidence **
***** Not Defined, Unknown, Confirmed, Reasonable [CVSS Temporal]



***[#pink] **Vulnerability**


****_ **Exploitability Metrics ** [CVSS Base Metric]
*****_ <:green_book:> **Attack Vector** 
*****_ <:green_book:> **Attack Complexity** 
*****_ <:green_book:> **Attack Requirements** [CVSS Base Metric v4]
*****_ <:green_book:> **Privileges Required** 
*****_ <:green_book:> **User Interaction** 



***[#pink] **Technical Impact**

****_ <:green_book:> **Vulnerable System Impact Metrics** [CVSS Base Metric]
*****_ <:green_book:> **Confidentiality**  
*****_ <:green_book:> **Integrity**
*****_ <:green_book:> **Availability** 
*****_ <:green_book:> --Scope-- [replaced with Subsequent System Impact Metrics in CVSS v4]


****_ <:green_book:> **Subsequent System Impact Metrics** [CVSS Base Metric v4]
*****_ <:green_book:> **Confidentiality** 
*****_ <:green_book:> **Integrity** 
*****_ <:green_book:> **Availability** 

****_ <:green_book:> **Vulnerabilities by Impact Types** [CVEDetails.com]
*****_ <:green_book:> **Privilege Escalation** 
*****_ <:green_book:> **Code Execution** 
*****_ <:green_book:> **Denial of Service ** 
*****_ <:green_book:> **Information Leak ** 
*****_ <:green_book:> **Bypass** 

****_ <:green_book:> **Microsoft Exploitability Index** [Microsoft Products]
*****_ <:green_book:> **Elevation of Privilege** 
*****_ <:green_book:> **Remote Code Execution** 
*****_ <:green_book:> **Denial of Service ** 
*****_ <:green_book:> **Information Disclosure ** 
*****_ <:green_book:> **Security Feature Bypass** 
*****_ <:green_book:> **Spoofing** 
*****_ <:green_book:> **Tampering** 


**[#orange]:==Per Asset 
----
----
----;

*** **Impact** <<asset>>

****_ **Exploitable**
*****_ <:closed_book:> **Affected stack component versions in place** e.g. SpringShell Spring Framework exploitability depended on certain JDK versions
*****_ <:closed_book:> **Reachable** e.g. vulnerable function called by Application or callable (Tool e.g. SCA Reachability Analysis)
*****_ <:closed_book:> <:writing_hand:> **Compensating controls in place** e.g. WAF, SW configuration

****_ **System Exposure** 
*****_ <:closed_book:> <:writing_hand:> **Asset Inventory **
***** Small, Controlled, Open [CMU SEI SSVC] 

****_ <:closed_book:> <:writing_hand:> **Asset Value <Asset Inventory>**
*****_ **Value of the data it processes/serves**
*****_ **Geo location (Regulatory)**
*****_ **Performing Critical function aka Critical Product or Crown Jewel**

*****_ **Requirements for Confidentiality, Integrity, Availability (CIA) **
****** None, Low, Medium, High [CVSS Environmental]

*****_ **Loss** 
****** Productivity, Response, Replacement, Reputation, Competitive advantage, Judgments and fines [Factor Analysis of Information Risk (FAIR)]

*****_ **Impact** 
****** the impact on the Confidentiality/Integrity/Availability of the platform/tenants/data involved by the successful exploitation of the security vulnerability found [Vulnerability Impact Scoring System (VISS)]

*** **Likelihood** <<asset>>
****_ <:closed_book:> **Incident Response** has the Asset been attacked?
****_ <:closed_book:> **Number of assets with that CVE (SBOMs)**
****_ <:closed_book:> **Number of instances of that CVE (SBOMs)**
****_ **Vulnerability Chaining**
****_ <:dollar:> **Average Time to Exploit Product (VendorDB)**
****_ <:dollar:> **Frequency of Exploit for the Product (VendorDB)**


** **Remediation** <<remediation>> 
***_ **Remediation Level: patch available?**
****_ <:green_book:> <:dollar:> ** Tool e.g. SCA**
****_ <:green_book:> <:dollar:> ** Vendor DBs** 

**** Not Defined, Official Fix, Temporary Fix, Workaround, Unavailable [CVSS Temporal]
**** Available, Unavailable [CISA SSVC]
**** Fix, Workaround [CISA SSVC]
***_ <:closed_book:> **System Change difficulty: quick fix or major refactor?**
****_ <:busts_in_silhouette:> **Developers**
**** Low, High [CISA SSVC]
***_ <:closed_book:> **Fix/Merge Confidence** Can we apply the fix? Will the fix break something?
****_ <:green_book:> <:dollar:> **% (Tool e.g. SCA)**
****_ <:busts_in_silhouette:> **Developers**
***_ <:closed_book:> **Package upgrade value**
****_ how many risky CVEs are fixed by updating a package of any version to latest/target version? (SBOMs)
***_ <:closed_book:> **Effort**
****_ <:busts_in_silhouette:> **Developers**
**** CMU SEI discusses “unit of work” for Remediation activitities

legend
    |= Icon |= Description |
    |  <:closed_book:>  | Internal |
    |  <:green_book:>   | Open and available to anyone |
    |  <:dollar:>       | Paid product  |
    |  <:writing_hand:> | Manual |
    |  <:black_square_button:> | Relevant values defined in a standard |
endlegend

center footer <:triangular_flag_on_post:> The data sources for Threat and Vulnerability give information for individual vulnerabilities. For an asset, we're concerned about all the vulnerabilities and threats - including if these are chainable \n <:triangular_flag_on_post:> "vulnerabilities with published exploit code are as much as 7 times as likely to be exploited in the wild" "If it’s ‘weaponized’ (think metasploit), the odds of a vulnerability being exploited in the wild really balloon from about 3.7% to 37.1%." https://www.cyentia.com/github-a-source-for-exploits/ \n <:triangular_flag_on_post:> GitHub Advisory DB, VendorDBs, Tool-providers provide additional vulnerability information that may not have an associated CVE - or may have data that differs from the NVD CVE data. \n <:triangular_flag_on_post:>Asset (~Product) contains Package that contains CVE

@endwbs

Themes
-------
This gives the best clarity
!theme plain 

Other themes considered:
!theme metal
!theme materia
!theme cerulean
!theme hacker

icons
------
https://plantuml.com/creole
https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhDpS_AL31qC-5oICrB0Oe00000

preprocessor
------------
Consider using plantuml pre-processor in future to maintain definitions in one place/file. 
define: !$cisa_kev = "<:green_book:> **CISA Known Exploited Vulnerabilities (CISA KEV)**"
use: $cisa_kev 
