' /* Copyright Yahoo, Licensed under the terms of the Apache 2.0 license. See LICENSE file in project root for terms. */

@startwbs
!theme plain

<style>
wbsDiagram {
  .riskremediation {
      BackgroundColor lightblue
  }
  .risk {
      BackgroundColor pink
  }
  .remediation {
      BackgroundColor lightgreen
  }
  
}

</style>

Title Risk Remediation Taxonomy for CVEs

* **Risk Remediation** <<riskremediation>>
** **Risk** <<risk>>

*** **Threat** <<risk>>
****_ **Likelihood of Exploit**
*****_ **Known Actively Exploited in your Organization**
******_ <:closed_book:> **Bug Bounty** has the CVE been exploited?
******_ <:closed_book:> **Incident Response** has the CVE been exploited? 
******_ <:closed_book:> **Incident Response** has the Asset been attacked?

*****_ **Known Actively Exploited in the Wild**
******_ <:green_book:> **CISA Known Exploited Vulnerabilities (CISA KEV)**
******_ <:dollar:> **Vendor DBs** (typicaly include CISA KEV data)
******_ <:green_book:> <:dollar:> **Cyber Threat Intelligence (CTI)** e.g. social media

*****_  <:green_book:> **Probability of Exploitation Activity in the next 30 days % **(EPSS Exploit Prediction Scoring System v3)
******_ **Exploitation activity in the wild (ground truth)** Fortinet, AlienVault, ShadowServer, GreyNoise
******_ **Publicly available exploit code** ExploitDB, GitHub, MetaSploit
******_ CVE listed on CISA KEV, Google Project Zero, Trend Micro's Zero Day Initiative
******_ **Social Media** Mentions/discussion on Twitter
******_ **Offensive security tools and scanners** Intrigue, sn1per, jaeles, nuclei
******_ **References with labels** MITRE CVE List, NVD
******_ **Keyword description of the vulnerability** Text description in MITRE CVE List
******_ **CVSS metrics** National Vulnerability Database (NVD)
******_ **CWE** National Vulnerability Database (NVD)
******_ **Vendor labels** National Vulnerability Database (NVD)
******_ **Age of the vulnerability** Days since CVE published in MITRE CVE list


*****_ **Known Exploit Available**
******_ <:dollar:>** Vendor DBs** which include data about (weaponized) vulnerabilities from tools like Metasploit
******_ <:green_book:> <:dollar:>  **Cyber Threat Intelligence (CTI)** e.g. social media
******_ <:green_book:> <:dollar:> **Exploit Code Maturity **
*******_ <:dollar:> **Vendor DBs** 
******* Not Defined, Unproven, Proof-Of-Concept, Functional, High [CVSS Temporal]
******* e.g. public, poc_public, virus_malware, wormified, private, commercial, exploit_unknown, unknown
*****_ <:dollar:> **Frequency of Exploit (VendorDB)**
*****_ <:dollar:> **Average Time to Exploit Product (VendorDB)**
****_ **System Exposure** 
*****_ <:closed_book:> <:writing_hand:> **Asset Inventory **
***** Small, Controlled, Open [CMU SEI SSVC] 
****_ <:green_book:> <:dollar:> **Report Confidence **
***** Not Defined, Unknown, Confirmed, Reasonable [CVSS Temporal]


*** **Impact** <<risk>>
****_ <:closed_book:> <:writing_hand:> **Asset Value <Asset Inventory>**
*****_ **Value of the data it processes/serves**
*****_ **Performing Critical function aka Critical Product**
*****_ **Loss** 
****** Productivity, Response, Replacement, Reputation, Competitive advantage, Judgments and fines [Factor Analysis of Information Risk (FAIR)]
****_ <:closed_book:> **Number of assets with that CVE (SBOMs)**
****_ <:closed_book:> **Number of instances of that CVE (SBOMs)**
****_ **Requirements for Confidentiality, Integrity, Availability (CIA) **
*****_ <:closed_book:> <:writing_hand:> **Asset Inventory**
****** None, Low, Medium, High [CVSS Environmental]

*** **Vulnerability** <<risk>>
****_ **Exploitable**
*****_ <:closed_book:> **Affected stack component versions in place** e.g. SpringShell Spring Framework exploitability depended on certain JDK versions
*****_ <:closed_book:> **Reachable** e.g. vulnerable function called by Application or callable (Tool e.g. SCA Reachability Analysis)
*****_ <:closed_book:> <:writing_hand:> **Compensating controls in place** e.g. WAF, SW configuration
****_ **Exploitability metrics **
*****_ <:green_book:> **Attack Vector** [CVSS Base Score]
*****_ <:green_book:> **Attack Complexity** [CVSS Base Score]
*****_ <:green_book:> **Privileges Required** [CVSS Base Score]
*****_ <:green_book:> **User Interaction** [CVSS Base Score]

****_ **Impact metrics **
*****_ <:green_book:> **Confidentiality, Integrity, Availability (CIA):** None, Low, High [CVSS Base Score]
****_ **Scope** 
*****_ <:green_book:> Unchanged, Changed [CVSS Base score]



** **Remediation** <<remediation>> 
***_ **Remediation Level: patch available?**
****_ <:green_book:> <:dollar:> ** Tool e.g. SCA**
****_ <:green_book:> <:dollar:> ** Vendor DBs** 

**** Not Defined, Official Fix, Temporary Fix, Workaround, Unavailable [CVSS Temporal]
**** Available, Unavailable [CISA SSVC]
**** Fix, Workaround [CISA SSVC]
***_ <:closed_book:> **System Change difficulty: quick fix or major refactor?**
****_ <:busts_in_silhouette:> **Developers**
**** Low, High [CISA SSVC]
***_ <:closed_book:> **Fix/Merge Confidence** Can we apply the fix? Will the fix break something?
****_ <:green_book:> <:dollar:> **% (Tool e.g. SCA)**
****_ <:busts_in_silhouette:> **Developers**
***_ <:closed_book:> **Package upgrade value**
****_ how many risky CVEs are fixed by updating a package of any version to latest/target version? (SBOMs)
***_ <:closed_book:> **Effort**
****_ <:busts_in_silhouette:> **Developers**
**** CMU SEI discusses “unit of work” for Remediation activitities

legend
    |= Icon |= Description |
    |  <:closed_book:>  | Internal |
    |  <:green_book:>   | Open and available to anyone |
    |  <:dollar:>       | Paid product  |
    |  <:writing_hand:> | Manual |
    |  <:black_square_button:> | Relevant values defined in a standard |
endlegend

center footer <:triangular_flag_on_post:> GitHub Advisory DB, VendorDBs, Tool-providers provide additional vulnerability information that may not have an associated CVE - or may have data that differs from the NVD CVE data. \n <:triangular_flag_on_post:>Asset (~Product) contains Package that contains CVE

@endwbs

Themes
-------
This gives the best clarity
!theme plain 

Other themes considered:
!theme metal
!theme materia
!theme cerulean
!theme hacker

icons
------
https://plantuml.com/creole
https://www.plantuml.com/plantuml/svg/SoWkIImgAStDuKhDpS_AL31qC-5oICrB0Oe00000

preprocessor
------------
Consider using plantuml pre-processor in future to maintain definitions in one place/file. 
define: !$cisa_kev = "<:green_book:> **CISA Known Exploited Vulnerabilities (CISA KEV)**"
use: $cisa_kev 
